name: Continuous Integration
on: [push, pull_request]
jobs:
  continuous-integration:
    runs-on: ubuntu-18.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run-script buildSharedLint
    - run: npm run-script build
    - run: aws s3 sync dist s3://www.sunruse.co.uk/quiz --acl public-read --exclude "index.html"
      if: github.ref == 'refs/heads/master'
    - run: aws s3 sync dist s3://www.sunruse.co.uk/quiz --acl public-read --exclude "*" --include "index.html"
      if: github.ref == 'refs/heads/master'
    - run: aws lambda update-function-code --function-name sunruse-quiz --zip-file fileb://host/aws/server/event-handler/dist/index.zip --publish
      if: github.ref == 'refs/heads/master'
